"""T11 (E9) summary: SimToM-style ToM baseline vs heavy-load pragmatic inference.

Same 2,000 MIC items, same gold labels, same SFT recipe/seed, same eval pipeline
(MIC-500; BBQ generation + Qwen3-14B option-matching judge).
CONFOUND (stated wherever reported): ToM inference text was verbalized by a local
Qwen3-14B teacher (the paper's DeepSeek key is no longer valid), while the pragmatic
model's inference text came from DeepSeek.
Writes rebuttal/results/tom_baseline.md
"""
import json
import numpy as np
from scipy.stats import binomtest, wilcoxon

B = "."
prag = json.load(open(f"{B}/rebuttal/data/eval_pragmaticFull.json"))
tom = json.load(open(f"{B}/rebuttal/data/eval_ToM.json"))


def mcnemar(pairs):
    b = sum(1 for x, y in pairs if x and not y)
    c = sum(1 for x, y in pairs if not x and y)
    return b, c, (binomtest(b, b + c, 0.5).pvalue if b + c else 1.0)


lines = ["# T11 (E9): SimToM-style ToM baseline (reviewer LVZS Q3)", "",
         "Perspective-inference steps (speaker perspective -> affected-party perspective ->",
         "perspective-grounded judgment -> perspective-grounded revision) trained through the",
         "same pipeline as the paper's methods (same 2,000 MIC items, gold labels, recipe, seed,",
         "checkpoint-375, eval).",
         "",
         "**Teacher confound (must be stated):** ToM inference text was generated by a local",
         "Qwen3-14B teacher because the original DeepSeek API key is invalid; the pragmatic",
         "model's inference text came from DeepSeek. The pragmatic comparator below is our",
         "seed-matched retrain evaluated through the identical pipeline.", ""]

pm, tm = prag["MIC"], tom["MIC"]
jp = [(int(r1["pred"] == r1["gold"]), int(r2["pred"] == r2["gold"]))
      for r1, r2 in zip(pm["records"], tm["records"])]
b, c, p = mcnemar(jp)
rl = [(r1["rougeL"], r2["rougeL"]) for r1, r2 in zip(pm["records"], tm["records"])
      if r1["rougeL"] is not None and r2["rougeL"] is not None]
wp = wilcoxon([a for a, _ in rl], [b_ for _, b_ in rl]).pvalue if rl else float("nan")
lines += ["## MIC (n=500)", "",
          "| Metric | Heavy-load pragmatic (retrain) | ToM (SimToM-style) | test |",
          "|---|---|---|---|",
          f"| Judgment accuracy | {pm['judgment_acc']:.3f} | {tm['judgment_acc']:.3f} | McNemar b={b}, c={c}, p={p:.2e} |",
          f"| ROUGE-L (disagree revisions) | {pm['rougeL_disagree']:.3f} | {tm['rougeL_disagree']:.3f} | Wilcoxon p={wp:.3f} (n={len(rl)}) |",
          ""]

lines += ["## BBQ correction accuracy (Qwen3-14B judge)", "",
          "| Bias | Pragmatic (retrain) | ToM | McNemar |", "|---|---|---|---|"]
for bias in ["gender", "nationality", "disability"]:
    pr, tr = prag[f"BBQ_gen/{bias}"], tom[f"BBQ_gen/{bias}"]
    pairs = [(r1["judge_correct"], r2["judge_correct"]) for r1, r2 in zip(pr, tr)]
    b, c, p = mcnemar(pairs)
    lines.append(f"| {bias} | {np.mean([x for x,_ in pairs]):.3f} | {np.mean([y for _,y in pairs]):.3f} | b={b}, c={c}, p={p:.3f} |")

lines += ["", "## Reading (honest)",
          "- The ToM baseline is COMPETITIVE on these heavy-load tasks: higher MIC judgment accuracy,",
          "  lower revision ROUGE-L, and mixed/comparable BBQ correction accuracy vs our pragmatic",
          "  retrain. It does not obviously underperform the structured pragmatic inference at this",
          "  checkpoint under this judge.",
          "- Interpretation limits: (i) teacher confound above; (ii) ToM was only tested on the",
          "  heavy-load side — it does not address the paper's central inferential-load variable",
          "  (light/heavy division and their crossover), which is carried by Tables 2-4;",
          "  (iii) single seed/checkpoint/judge.",
          "- For the rebuttal: present ToM as a *newly added competitive baseline* whose full",
          "  cross-task evaluation (toxicity + jailbreak, multiple seeds, matched teacher) is",
          "  promised for the revision, rather than claiming pragmatic inference beats it outright."]

open(f"{B}/rebuttal/results/tom_baseline.md", "w").write("\n".join(lines) + "\n")
print("\n".join(lines[16:]))
