"""T8 (E7): Worked training-instance examples + dataset stats (reviewer xnDd Q1).

Pulls REAL examples from the DeepSeek-verbalized training data
(experiments/deepseek/...) and assembles the exact final training strings
using the same logic as myMain.py:prepare_training_data4MIC.
Writes rebuttal/results/data_examples.md
"""
import json
import glob

B = "."
MFT_PREFIX = ("There are the six moral foundations. Care: wanting someone or something to be safe, "
              "healthy, and happy. Fairness: wanting to see individuals or groups treated equally or "
              "equitably. Liberty: wanting people to be free to make their own decisions. Loyalty: "
              "wanting unity and seeing people keep promises or obligations to an in-group. Authority: "
              "wanting to respect social roles, duties, privacy, peace, and order. Sanctity: wanting "
              "people and things to be clean, pure, innocent, and holy.")


def load_all(pattern):
    out = []
    for fp in sorted(glob.glob(pattern)):
        d = json.load(open(fp))
        out.append(d if isinstance(d, dict) else d[0])
    return out


def assemble(it, setting):
    q = it["Question"].strip().replace("\n", " ")
    a = it["Answer"].strip().replace("\n", " ")
    wa = it.get("worker_answer", "").strip().replace("\n", " ")
    judg = {"agree": "agree", "disagree": "disagree", "neutral": "agree"}[it["judg2reply"].strip()]
    inf = it[f"inference4{setting}"][0]["response"].strip().replace("\n", " ")
    if setting == "pragmatic":
        text = f'{MFT_PREFIX} <Prompt>: "{q}"; <Reply>: "{a}". ###Diagnosis: {inf} '
        if judg == "agree" and "(5)" in text:
            text = text.split("(5)")[0].strip()
    else:
        text = f'<Prompt>: "{q}"; <Reply>: "{a}". ###Diagnosis: {inf} '
        if judg == "agree" and "(2)" in text:
            text = text.split("(2)")[0].strip()
    if judg != "agree":
        text += f'Therefore, the <Revised Reply> is "{wa}"'
    return text


prag = load_all(f"{B}/experiments/deepseek/MIC/Correct/pragmatic/*.json")
sema = load_all(f"{B}/experiments/deepseek/realtoxicity/Correct/semantic/*.json")

# the assembled 2000-instance training file (1000 agree / 1000 disagree) holds the
# exact final training strings; take the heavy-load disagree example from there
train_lines = open(f"{B}/experiments/MIC.Correct.pragmatic.llama3.2-3B.2000.train.1.txt").read().split("\n")
prag_dis_text = next(l for l in train_lines
                     if "Therefore, the <Revised Reply> is" in l and "(5)" in l and len(l) < 3500)
prag_agr = next(x for x in prag if x["judg2reply"].strip() == "agree")
sema_dis = next(x for x in sema if x["judg2reply"].strip() == "disagree" and x.get("worker_answer"))
sema_agr = next(x for x in sema if x["judg2reply"].strip() == "agree")

n_dis_train = sum(1 for l in train_lines if "Therefore, the <Revised Reply> is" in l)
n_sema_dis = sum(1 for x in sema if x["judg2reply"].strip() == "disagree")

mic_train = json.load(open(f"{B}/dataset/MIC.train.json"))
mic_dev = json.load(open(f"{B}/dataset/MIC.dev.json"))

lines = [
    "# T8 (E7): Worked training-instance examples + dataset stats",
    "",
    "## Dataset sizes (for restructured Section 4.1)",
    f"- MIC (heavy-load fine-tuning): {len(mic_train)} train / {len(mic_dev)} dev items "
    "(gold moral foundations, judgments, and human revised replies from MIC annotations; "
    "DeepSeek only verbalizes the intermediate steps).",
    f"- RealToxicityPrompts (light-load fine-tuning): 2,000 sampled (prompt, continuation) pairs; half "
    "with continuation toxicity < 0.1, half > 0.8 (PerspectiveAPI); toxic continuations revised by "
    "DeepSeek and accepted only when revised toxicity < 0.1. Cached test files score 300 items/run.",
    "- BBQ (test-only): gender 550 / nationality 300 / disability 152, balanced biased vs non-biased.",
    "- JailbreakBench (test-only): 420 items = 210 harmful-behavior samples + 210 Alpaca benign pairs.",
    f"- Assembled heavy-load SFT file (2000 instances): {n_dis_train} disagree / "
    f"{len(train_lines) - n_dis_train} agree; every disagree instance ends with Step 5 + revised reply.",
    "",
    "## Heavy-load training instance (MIC, judgment = disagree)",
    "",
    "Final assembled training text (input + supervision target, exactly as fed to SFT;",
    "gold MFT/judgment/revised reply come from MIC human annotations, DeepSeek verbalizes the steps):",
    "", "```", prag_dis_text, "```", "",
    "## Heavy-load training instance (MIC, judgment = agree) — steps truncate before Step 5",
    "", "```", assemble(prag_agr, "pragmatic"), "```", "",
    "## Light-load training instance (RealToxicityPrompts, toxic continuation)",
    "",
    f"- x_p: {sema_dis['Question'].strip()[:200]}",
    f"- x_r: {sema_dis['Answer'].strip()[:200]}",
    "- y_r generated by DeepSeek, accepted only if Perspective toxicity < 0.1:",
    "", "```", assemble(sema_dis, "semantic"), "```", "",
    "## Light-load training instance (non-toxic continuation, judgment = agree)",
    "", "```", assemble(sema_agr, "semantic"), "```", "",
]
open(f"{B}/rebuttal/results/data_examples.md", "w").write("\n".join(lines) + "\n")
print("\n".join(lines[:22]))
print("... wrote results/data_examples.md")
